"""Generate accounts.csv for sf data upsert bulk from Ready For Accounts sheet data."""
import csv
import sys

ORG_RECORD_TYPE = "012f2000000ww92AAA"

# Raw rows from Ready For Accounts tab (A1:AQ30), rows 2-30 (header is row 1)
# Indices: 0=Name,1=Location,2=Area,3=AccountInfo,4=DocReq,5=GrantAmt,6=DueDate,
#  7=ContactPerson,8=Title,9=Email,10=EIN,11=AppStatus,12=Outreach,13=Notes,
#  21=URLFromName,23=URLFromArea,24=URLAcctInfo,25=URLDocReq,26=URLGrant,
#  27=URLDueDate,28=URLOutreach,29=ResearchLinks,42=ExternalID
ROWS = [
    ['Hispanic Federation 2026 UPLift New York State','New York City','Hispanic Federation (HF) is issuing a Request for Proposals (RFP) to member agencies and allies for the\nimplementation of a targeted campaign to provide health access and literacy, economic empowerment\nprogramming, and basic needs services to New York’s communities of color, particularly\nbilingual/bicultural communities.','Portal ','- Must be a 501(c)(3) nonprofit or have a fiscal sponsor\n- Must serve communities in New York State\n- Must provide culturally and linguistically responsive services\n- Programs must align with one or more priority areas:\n1. Language access\n2. Civic education\n3. Workforce training\n4. Educational advancement\n- Must demonstrate community impact and organizational capacity\n- Grant requests cannot exceed 30% of the organization\'s annual operating budget\n- Must submit required organizational documents (IRS determination letter, budget, etc.)\n- Programs should support underserved and/or Latino communities and improve socioeconomic outcomes.','','February 6, 2026','Gonzalo Loayza','','gloayza@hispanicfederation.org','13-3573852','Submitted 2/5/2026','','','','','','','','','','https://www.hispanicfederation.org/','Hispanic Federation 2026 UPLift New York State','','','','','','#ERROR!','#ERROR!','Gonzalo Loayza','Gonzalo Loayza','','','','','','','gloayza@hispanicfederation.org','gloayza@hispanicfederation.org','','','hispanicfederation2026upliftnewyorkstate'],
    ['ViaPath Foundation','Nationwide','Empowering at-risk communities by supporting youth, advancing advocacy, and building meaningful career pathways','ViaPath Foundation ','- Be a 501(c)(3) nonprofit organization or apply using a fiscal sponsor \n\n- Provide proof of IRS federal tax-exempt status \n\n- Submit an anti-discrimination statement adopted by the board \n\n- Provide financial documentation, including budget information and list of major contributors \n\n- Complete required narrative sections including evaluation expectations and inclusiveness ','cap of $50,000 over a three-year period','February 20, 2026','Lisa Garcias','Director','info@viapath-foundation.org','87-4626071','Submitted 2/20/2026','','','','','','','','','','https://www.viapathfoundation.org/#our-mission','ViaPath Foundation','','https://www.viapathfoundation.org/news/viapath-foundation-opens-2025-grant-application-process/','','','','','https://www.viapathfoundation.org/news/viapath-foundation-opens-2025-grant-application-process/','Lisa Garcias','Lisa Garcias','','','Director','Director','','','info@viapath-foundation.org','info@viapath-foundation.org','','','viapathfoundation'],
    ['Spectrum Digital Education Grant','Communities in Spectrum market','digital skills training, technology access, digital literacy, workforce readiness, and educational opportunitie','Spectrum Digital Education Grant','Focus on families or seniors.\nBe able to report to Spectrum the following metrics: number of people impacted, population served and demographics.\nPartner with low-income rural and/or urban communities.\nBe an existing program, already serving our community.\nMeet the unique needs of its community and align with the nonprofit\'s current mission.\nHave a lasting, meaningful and tangible impact (e.g. development of a new digital site or app, expansion of the capacity of a digital learning center, creation of a mobile computer lab, etc.)','$2,500 - $50,000','February 27, 2026','','','DigitalEdGrant@spectrum.com','N/A','Submitted 2/27/2026','','','','','','','','','','https://corporate.charter.com/digital-education/grants','Spectrum Digital Education Grant','','https://forms.benevity.org/7d8320b4-3a3d-4b7d-9c72-d8f2abc91337?submissionKey=4d6422a8-4029-4337-8037-947f9768819e','','','','','https://forms.benevity.org/7d8320b4-3a3d-4b7d-9c72-d8f2abc91337?submissionKey=4d6422a8-4029-4337-8037-947f9768819e','','','','','','','','','DigitalEdGrant@spectrum.com','DigitalEdGrant@spectrum.com','','','spectrumdigitaleducationgrant'],
    ['Mary S. Mulligan Charitable Trust (Bank of America)','New York, Pennsylvania, Michigan, Massachusetts, and other states.','arts, culture, and humanities, education, health, human services, and general charitable purposes including religious, scientific, literary, and educational programming or prevention of cruelty to children or animals.','Mary Mulligan Portal','Must be a tax-exempt nonprofit (501(c)(3)) organization.\n\nRecipients appear to be other charitable nonprofits in areas aligned with the Trust\'s interests.','  $2,000 up to about $36,150','March 1 ; September 1','','','ct.grantmaking@bofa.com','16-6076169','Submitted 3/1/2026','','','','','','','','','','https://www.bankofamerica.com/philanthropic/foundation/?fnId=456','Mary S. Mulligan Charitable Trust (Bank of America)','#ERROR!','https://bofa-gh.foundationsource.com/login','','','','','#ERROR!','','','','','','','','','ct.grantmaking@bofa.com','ct.grantmaking@bofa.com','','','marysmulligancharitabletrustbankofamerica'],
    ['American Eagle Foundation','United States + Canada','Mental health & well-being of young people','American Eagle Portal','Organizations that are certified 501(c)3 nonprofits in the United States or are registered charities in Canada are eligible to apply. Individuals, corporations and other entities will not be accepted. The proposal must show that funding will be used to support programming or goals that positively impacts the mental health and well-being of teens and/or young adults to empower authenticity and a better future for all.\n\nOrganizations can apply and receive funding once per year. The organization will need to spend the funding and submit a final report before reapplying. Reapplying for funding does not guarantee that you will be awarded. ','$5,000 - $15,000','\n March 2, 2026; August 10, 2026','','','AEFoundation@ae.com','25-1827476','Submitted 3/2/2026','','','','','','','','','','https://blog.ae.com/ae-foundation-grant-guidelines/','American Eagle Foundation','','https://webportalapp.com/sp/login/aefoundation','','','','','https://webportalapp.com/sp/login/aefoundation','','','','','','','','','AEFoundation@ae.com','AEFoundation@ae.com','','','americaneaglefoundation'],
    ['The Frances L. & Edwin L. Cummings Memorial Fund','New York City (Bronx, Manhattan, Queens, Brooklyn, Staten Island) and the five Northeastern New Jersey counties of Bergen, Essex, Hudson, Passaic, and Union.','Education, youth, women','Frances & Edwin Fund','Proposal Requirements','Average - $70,000','4/1/2026; 10/1/2026',' ','','info@cummingsfund.org','13-6814491','Submitted 4/1/2026','','','','','','','','','','https://cummingsfund.org/areas-of-interest/','The Frances L. & Edwin L. Cummings Memorial Fund','','https://cummingsfund.org/proposal-requirements/?utm_source=chatgpt.com','https://cummingsfund.org/proposal-requirements/','','','','https://cummingsfund.org/proposal-requirements/?utm_source=chatgpt.com\nhttps://cummingsfund.org/proposal-requirements/','','','','','','','','','info@cummingsfund.org','info@cummingsfund.org','','','thefrancesledwinlcummingsmemorialfund'],
    ['Laura B. Vogler Foundation','New York City, Long Island, and Westchester, NY.','health, well-being, education of children, disadvantaged populations, and the elderly; generally program/project support.','Laura B. Volger Application (submit via email to voglerfound@gmail.com)','are located in New York City or Long Island;\n\nare tax exempt under 501 (c) (3) of the Internal Revenue Code;\n\npromote the health, well being, and education of children, the disadvantaged and the elderly; and\n\nprimarily fund specific programs or projects rather than general operating support or capital programs.','$3,000–$4,000','July 1; October 1','','','voglerfound@gmail.com','11-6022241','Submitted 4/1/2026','','','','','','','','','','https://sites.google.com/site/voglerfoundation/grant-application?authuser=0','Laura B. Vogler Foundation','','https://drive.google.com/file/d/0Bz3iBm8H_oMTdDYwamx3VVFqUlE/view?resourcekey=0-puWtKUW4I3RpiFb5jMq42Q','','','','','https://drive.google.com/file/d/0Bz3iBm8H_oMTdDYwamx3VVFqUlE/view?resourcekey=0-puWtKUW4I3RpiFb5jMq42Q','','','','','','','','','voglerfound@gmail.com','voglerfound@gmail.com','','','laurabvoglerfoundation'],
    ['William T. Grant Foundation (Youth Service Improvement Grant)','New York City','Financial management, board recruitment and development, human resource management, staff training, fundraising, strategic planning, information technology, leadership development, communications, evaluation systems.','William Grant Application Portal','William T. Grant Application Guidelines','$25,000','April 1, 2026','Nancy Rivera-Torres','Grants Administrator','nrivera@wtgrantfdn.org','13-1624021','Submitted 4/1/2026','','','','','','','','','','https://wtgrantfoundation.org/funding/youth-service-capacity-building-grants','William T. Grant Foundation (Youth Service Improvement Grant)','','https://wtg.smartsimple.com/s_Login.jsp','https://wtgrantfoundation.org/wp-content/uploads/2026/01/2026-Application-Guide-YSIG.pdf','','','#ERROR!','#ERROR!','Nancy Rivera-Torres','Nancy Rivera-Torres','','','Grants Administrator','Grants Administrator','','','nrivera@wtgrantfdn.org','nrivera@wtgrantfdn.org','','','williamtgrantfoundationyouthserviceimprovementgrant'],
    ['UnidosUS – Pioneras en STEM','United States','STEM education, Latina women, workforce development, higher education, leadership, minority communities',' Portal','Application Requirements:\n\n• Proof of nonprofit/affiliate eligibility or fiscal sponsorship if allowed.\n• Description of target students, especially Latina high school students.\n• STEM curriculum or program model.\n• Mentorship/career exposure plan.\n• Participant recruitment and retention plan.\n• Outcome tracking plan for graduation, postsecondary enrollment, STEM interest, career exposure, and completion.\n• Staff qualifications and implementation timeline.\n• Program budget and sustainability plan.','$20,000','April 1','—','—','—','86-0212873','Submitted 4/1','','','','','','','','','','https://unidosus.org/','UnidosUS – Pioneras en STEM','','https://www.ccnsfund.org/apply','','','','','https://www.ccnsfund.org/apply','—','—','','','—','—','','','','','','','unidosuspionerasenstem'],
    ['UnidosUS – Escaleras','United States','Education, workforce readiness, economic mobility, Latino communities, career pathways, youth development',' Portal','Application Requirements: \n\n• Youth college/career readiness program narrative.\n• Description of Latino high school youth served.\n• Curriculum or implementation plan.\n• Case management/student support model.\n• Internship, employer, college, or workforce partnerships.\n• Outcome plan for postsecondary enrollment, career readiness, leadership, financial empowerment, and persistence.\n• Staffing plan, timeline, budget, and evaluation plan.','$40,000','April 1','—','—','—','86-0212873','Submitted 4/1','','','','','','','','','','https://unidosus.org/','UnidosUS – Escaleras','','https://www.ccnsfund.org/apply','','','','','https://www.ccnsfund.org/apply','—','—','','','—','—','','','','','','','unidosusescaleras'],
    ['Mother Cabrini Health Foundation','New York State ','Improving health and well-being of vulnerable New Yorkers, enhancing equitable access to healthcare, supporting basic needs, strengthening the healthcare workforce, advancing mental and behavioral health, and funding projects that improve health outcomes for underserved populations across New York State.','Mother Cabrini Health Portal','- Must be a domestic 501(c)(3) public charity or exempt operating foundation in good standing with the IRS and NYS.\n- Must primarily serve New York State residents and benefit poor, disadvantaged, or underserved communities.\n- Applicant organizations should generally have an annual operating budget of at least $750,000 (per typical guidelines).\n- Projects must align with the Foundation\'s mission and meet one of the focus areas and demonstrate capacity to effectively carry out proposed programming.\n- Non-Catholic organizations are eligible; Catholic ethical principles guide funding but affiliation is not required.','$75,000+','2026 TBD','','','grantsupport@cabrinihealth.org','83-0590263','Submitted 4/23/2026','','','','','','','','','','https://www.cabrinihealth.org/grants-programs/#apply-grant','Mother Cabrini Health Foundation','','https://cabrinihealth.smartsimple.us/s_Login.jsp','','','','','https://cabrinihealth.smartsimple.us/s_Login.jsp','','','','','','','','','grantsupport@cabrinihealth.org','grantsupport@cabrinihealth.org','','','mothercabrinihealthfoundation'],
    ['Brooklyn Org','New York City and Hudson Valley','Youth, education, mental health, girls of color','Brooklyn Org Portal','- Be incorporated as a 501(c)3 nonprofit organization or be working under the auspices of an authorized fiscal sponsor\n\n- Have a minimum annual budget of $100,000. Grant awards will not exceed 20% of the applying organization\'s annual budget\n\n- Have a regular physical presence in Brooklyn. All non-Brooklyn-based organizations must apply for support for their relevant Brooklyn-based work','','\n\nSeptember 30th','','','programs@brooklyn.org','11-3422729','Submitted 4/23/2026','','','','','','','','','','https://brooklyn.org/how-to-apply-for-bko-funding/','Brooklyn Org','','https://www.grantinterface.com/Home/Logon?urlkey=brooklyncf','','','','','https://www.grantinterface.com/Home/Logon?urlkey=brooklyncf','','','','','','','','','programs@brooklyn.org','programs@brooklyn.org','','','brooklynorg'],
    ['NBCUniveral Local Impact Grant','All cities in NBC/Telemundo markets','Youth education/empowerment, next generation storytellers, amd community engagement','NBCUniversal Portal','- Must be an active 501(c)(3) nonprofit (EIN active for at least one year) or a fiscally sponsored organization (apply through fiscal sponsor)\n- Must have been in operation for at least one year\n- Revenue must exceed $100,000; total expenses must be between $100,000 and $1,000,000\n- Grant request cannot exceed 30% of total expenses\n- Must align with one of three focus areas: Youth Education and Empowerment, Next Generation Storytellers, or Community Engagement\n- Ineligible if the organization received $10,000+ annually from Comcast NBCUniversal, NBC/Telemundo-owned stations, or related entities in any of the past three years\nOnly one application allowed per Tax ID across all marke','No more than 30% of reported expenses','April 24, 2026','','','','51-0390132','Submitted 4/24/2026','','','','','','','','','','https://www.localimpactgrants.com/','NBCUniveral Local Impact Grant','','https://bbgm-apply.yourcausegrants.com/apply/application/2333439/forms/13536','','','','','https://bbgm-apply.yourcausegrants.com/apply/application/2333439/forms/13536','','','','','','','','','','','','','nbcuniverallocalimpactgrant'],
    ['Lawrence Foundation','United States','Environmental protection and conservation, human services including disaster relief, and other causes aligned with improving societal and ecological well-being.','Lawrence Application','Be tax-exempt under Section 501(c)(3) of the Internal Revenue Service Code or have a fiscal sponsor that has 501(c)(3) status and provides written authorization confirming its willingness to act as the fiscal sponsor.\n\nEngage in work that aligns with the Foundation\'s funding interests and priorities.\n','$5,000 - $10,000','April 30; October 31.','Lori Mitchell','Executive Director',' lori@thelawrencefoundation.org','','Submitted 4/30/2026','','','Deadline','','','','','','','https://thelawrencefoundation.org/application-process','Lawrence Foundation','','https://www.commongrantapplication.com/login.php?new=1','','','','','https://www.commongrantapplication.com/login.php?new=1','Lori Mitchell','Lori Mitchell','','','Executive Director','Executive Director','','','lori@thelawrencefoundation.org','lori@thelawrencefoundation.org','','','lawrencefoundation'],
    ['Acquis Foundation','New York City','Education, workforce training, and DOI','RFP','Applicants must be registered 501(c)(3) nonprofit organizations.\n\nMust be an established organization with a new idea, or an organization with existing infrastructure (not a grass roots organization).\n\nAlignment with Acquis Foundation\'s mission and values.\n\nOrganizations do not need to be headquartered in NYC, but their work must impact New York area communities.\n\nApplicants must consent to being featured on the Acquis Foundation\'s website, social media channels, and other publicly accessible platforms.','June 11','$46,142','','','acquis@acquisconsulting.com','87-1501756','Submitted 4/30/2026','','','','','','','','','','https://www.acquisconsulting.com/landing/foundation-rfp/','Acquis Foundation','','https://www.acquisconsulting.com/landing/foundation-rfp/','','','','','https://www.acquisconsulting.com/landing/foundation-rfp/','','','','','','','','','acquis@acquisconsulting.com','acquis@acquisconsulting.com','','','acquisfoundation'],
    ['The Slomo & Cindy Siivian Foundation','New York, New Jersey, and North Carolina','The Foundation makes grants to organizations that operate in one or more of the following subject areas: Education, Children’s Welfare, Medical Care, Medical Research, and Jewish Philanthropic Endeavors.','Portal',"501(c)(3) status with a public charity classification under IRC 509(a)(1) or 509(a)(2).Direct US IRS registration if operating as a foreign organization, as fiscal sponsors are not allowed.\n\nCore alignment with education, children's welfare, medical care, medical research, or Jewish philanthropy.\n\nGeographic presence located in or serving New York, New Jersey, or North Carolina.\n\nIRS Form 990 or 990EZ successfully filed with the IRS within the past two calendar years.\n\nCombined financial statement containing both a Balance Sheet and Income/Expense Statement if no 990 is available.English language and US dollar formatting on all uploaded alternative financial documents.\n\nSingle-document upload format for any alternative financial statements submitted to the portal.",'$20,000','6/1/2026','Daniel Komansky, David Grossman','President and Chairman of the Board of Directors, Treasurer and Board Member ','dkomansky@silvianfoundation.org, ','34-2037021','Submitted 5/15','','Expect to hear back with decision July 7, 2026','','','','','','','','https://silvianfoundation.org/','The Slomo & Cindy Siivian Foundation','','https://www.grantinterface.com/Opportunity/Catalog/Index?urlKey=silvianfoundation&accessCode=ASD2026LOI','','','','','https://www.grantinterface.com/Opportunity/Catalog/Index?urlKey=silvianfoundation&accessCode=ASD2026LOI','Daniel Komansky; David Grossman','Daniel Komansky',' David Grossman','','President and Chairman of the Board of Directors; Treasurer and Board Member','President and Chairman of the Board of Directors',' Treasurer and Board Member','','dkomansky@silvianfoundation.org','dkomansky@silvianfoundation.org','','','theslomocindysiivianfoundation'],
    ['New Profit','United States','Supports education, economic mobility, and democracy','Discovery Form','Legal: 501(c)(3) or U.S.-based fiscal sponsor.\n\nGeography: Must serve & operate in the United States.\n\nStage: 2+ years in operation; $250k–$2M annual budget (Catalyze) or $2M+ (Build).\n\nLeadership: Full-time CEO/ED; preference for “Proximate Leaders” (lived experience).','$110,000 (100k for organization; 10k for leadership development)','May 26','Danielle May','Director of Planning & Grants Management','danielle_may@newprofit.org','04-3396766','Submitted 5/22/2026','','','','','','','','','','','New Profit','','https://newprofit.tfaforms.net/18','','','','','https://newprofit.tfaforms.net/18','Danielle May','Danielle May','','','Director of Planning; Grants Management','Director of Planning',' Grants Management','','danielle_may@newprofit.org','danielle_may@newprofit.org','','','newprofit'],
    ['Tiger Foundation','Five boroughs of New York City','Youth organizing, education equity, mental health','Tiger Foundation Portal','The Tiger Foundation seeks:\n\n- Strong and consistent measurable outcomes over time\n\n- Skilled executive, program, and board leadership\n\n- Cost-effectiveness\n\n- Financial health and skilled fiscal management\n\n- Opportunity for broad impact (replicability, scale, and leverage of public and other private investment)\n\n- Efforts to engage clients and local community and to develop and refine models that are reflective of community needs\n\n- Applicants must be exempt from income taxes under section 501(c)(3) of the Internal Revenue Code.','$50,000 - $300,000 (Average $200,000)','Rolling','','','info@tigerfoundation.org','13-3532729','Submitted 5/26/2026','','','','','','','','','','https://tigerfoundation.org/funding-guidelines','Tiger Foundation','','https://rftf.givingdata.com/portal/campaign/TigerFoundationLOI?panelMode=signIn','','','','','https://rftf.givingdata.com/portal/campaign/TigerFoundationLOI?panelMode=signIn','','','','','','','','','info@tigerfoundation.org','info@tigerfoundation.org','','','tigerfoundation'],
    ['Sills Family Foundation','metro New York City and California','Early childhood education, environmental justice, arts and culture, families in crisis, criminal justice-impacted communities, refugees and migrants','No Application Posted, encourage to email: info@sillsfamilyfoundation.org','Must be a qualified 501(c)(3) nonprofit or equivalent.\n\nWork must align with the foundation\'s funding priorities: families in crisis, underserved communities, environmental justice, or arts and culture.\n\nGrants are typically by invitation, though Letters of Inquiry may be submitted for consideration.','$10,000 to $25,000','N/A','Run enitrely by board of family members who have little to no public presence','N/A','info@sillsfamilyfoundation.org','52-1790278','LOI Submitted','','LOI Submitted 4/21','','','','','','','','https://sillsfamilyfoundation.org/guidelines/','Sills Family Foundation','','','','','','','','Run enitrely by board of family members who have little to no public presence','Run enitrely by board of family members who have little to no public presence','','','N/A','N/A','','','info@sillsfamilyfoundation.org','info@sillsfamilyfoundation.org','','','sillsfamilyfoundation'],
    ['Robin Hood Foundation','New York City (five boroughs only)','Poverty, youth development, education, mental health','Robinhood Grant Application',"Organizations must: \n- Serve populations and operate within the five buroughs\n- Not currently be recieving support from Robinhood\n- Align with Robin Hood's life-stage approach (early childhood, school-age, young adults, adults & household supports)\n- A proven track record of being able to meet the needs of their population\n- High quality staff",'$100,000 - $1,600,000','Open year-round','','','Info@robinhood.org','13-3441066','Submitted 4/10/2026','','','','','','','','','','https://robinhood.org/our-work/become-grantee/','Robin Hood Foundation','','https://forms.robinhood.org/4718627?_gl=1*gywq7p*_gcl_au*NDI3NzUxNzAwLjE3NzAxNDM3NjI.','','','','','https://forms.robinhood.org/4718627?_gl=1*gywq7p*_gcl_au*NDI3NzUxNzAwLjE3NzAxNDM3NjI.','','','','','','','','','Info@robinhood.org','Info@robinhood.org','','','robinhoodfoundation'],
    ['Kars4Kids','United States','Supporting educational initiatives, youth development, mentorship, and community programs for children and young people that help them grow into productive, engaged members of their communities.','Kars4Kids Application','Applicant must be a U.S.-based, IRS-recognized 501(c)(3) nonprofit organization.\n\nThe nonprofit\'s primary mission should be serving children/youth with meaningful educational or developmental programs.\n\nPrograms should align with educational support, youth development, mentorship, or community empowerment initiatives.\n\nThe organization must operate with a secular, non-religious programmatic focus for this grant program.','$500 to $2,000','Open year-round','','','kars4kidscs@kars4kids.org','22-3746050','Submitted  ','','Rolling','','','','','','','','https://www.kars4kidsgrants.org/#apply','Kars4Kids','','https://www.kars4kidsgrants.org/#apply','','','','','https://www.kars4kidsgrants.org/#apply','','','','','','','','','kars4kidscs@kars4kids.org','kars4kidscs@kars4kids.org','','','kars4kids'],
    ['First Horizon Foundation ','New York City','Community well-being, financial education, economic opportunity, workforce development, education and leadership development, arts and culture, environmental sustainability.','First Horizon Application','- Tax info (ID/EIN, Form 990, 501(c)3 letter)\n- Basic info about organization (Name, type, mission statement, puropse, phone #, website, address, board of directors)\n- Info on community served (Age groups, ethnicity, SEC, etc). \n- Any prior relationship with the organization\n- Impact focus/areas\n- What the funds will be used for','$5,000 to $25,000','Rolling ','Abbey Lane','','abbey.lane@firsthorizon.com','62-1533987','In Progress','','Rolling','','','','','','','','https://firsthorizon.kadince.com/external/forms/c8daa6735c1ce25bb7d964156575deed','First Horizon Foundation','','https://firsthorizon.kadince.com/external/forms/c8daa6735c1ce25bb7d964156575deed','','','','','https://firsthorizon.kadince.com/external/forms/c8daa6735c1ce25bb7d964156575deed','Abbey Lane','Abbey Lane','','','','','','','abbey.lane@firsthorizon.com','abbey.lane@firsthorizon.com','','','firsthorizonfoundation'],
    ['Ichigo Foundation','New York City and California','College access, educational equity, first-generation student success, career readiness, economic mobility, youth development.','Ichigo LOI','- U.S.-based 501(c)(3) nonprofits\n- Focused on college access and postsecondary success\n- Serving first-generation, low-income, and historically underserved students\n- Demonstrating measurable educational and career outcomes\n- Working in educational equity, workforce development, or youth leadership\n- Serving students of color, immigrant communities, or justice-impacted populations\n- Operating scalable or high-impact programs','$25,000-$250,000','Rolling','Janel Callon','President','Janel.Callon@ichigofoundation.org','83-3528175','In Progress','','','','','','','','','','https://app.trytemelio.com/form/bf5e5e55-bff0-434c-bd95-c1523c0524ea','Ichigo Foundation','','https://app.trytemelio.com/form/bf5e5e55-bff0-434c-bd95-c1523c0524ea','','','','','https://app.trytemelio.com/form/bf5e5e55-bff0-434c-bd95-c1523c0524ea','Janel Callon','Janel Callon','','','President','President','','','Janel.Callon@ichigofoundation.org','Janel.Callon@ichigofoundation.org','','','ichigofoundation'],
    ['Arbor Rising','United States','Education, workforce development, youth development, economic mobility, poverty alleviation, capacity building.','Arbor LOI','- Have 501(c)(3) status or be fiscally sponsored by a 501(c)(3) organization\n- Be based in and operate within the lower 48 states\n- Have operated as an organization for at least 2 years, but no more than 15 years\n- Have at least four full-time, paid staff members\n- Have an annual operating budget of more than $500,000 and less than $3,000,000\n\nExceptions are made for:\n- Organizations less than five years old with budgets exceeding $3,000,000; and\n- Schools and school networks with overall budgets up to $30,000,000 that are launching or growing programs which advance student outcomes','$125,000','June 9','Domique ','Senior Associate','dominique@arborrising.org','27-4205023','In Progress',"- Email sent 5/21\n- Response: Thank you for reaching out. I'm pleased to virtually meet you. Arbor Rising is now accepting applications for the 2026-27 grant year. Unfortunately, due to the volume of applicants, we are not accepting meetings at this time. Instead, I invite you to take a look at our website to learn more about the opportunity, eligibility requirements, and application process. If this opportunity seems aligned with L.O.V.E.'s priorities, then I encourage you to complete a Letter of Inquiry no later than June 9, 5 PM Eastern.",'','','','','','','','','','https://app.trytemelio.com/form/bf5e5e55-bff0-434c-bd95-c1523c0524ea','','','','','https://app.trytemelio.com/form/bf5e5e55-bff0-434c-bd95-c1523c0524ea','Domique','Domique','','','Senior Associate','Senior Associate','','','dominique@arborrising.org','dominique@arborrising.org','','','arborrising'],
    ['Resort World Gives','New York City','Community & economic development, health & wellness, arts & culture, civic & public affairs, environment.','Resort World Portal','Eligibility:\n\n- Be a registered 501c3 or 501c6, or be fiscally sponsored by a 501c3 or 501c6\n- During the application process, you will be asked to upload your determination letter.\n- Provides services within one or more of Resorts World Gives’ key pillars:\n- Community & Economic Development\n- Health & Wellness\n- Environment\n- Civic & Public Affairs\n- Arts & Culture\n- Provides services within one or more of the regions where RWNYC and RWC operate.\n- Does not discriminate, either in employment or its delivery of services, on any basis prohibited by law or Resorts Worlds’ Equal - Employment Opportunity policies.\n\nApplication Materials:\n\n- Project description / Needs statement\n- Project budget\n- Project timeline\n- Letter of Support (Required)\n- This may come from a partner organization, another donor, a congressional representative, or an impacted individual. The letter should serve as a testimonial to your organization\'s prior work\n- Explanation of how Resorts World Gives partnership would be marketed','$50,000','November 1','Michelle Stoddart','Community Development Leader','michelle.stoddart@rwnewyork.com','27-3513153','In Progress','','','','','','','','','','','','','https://resortsworld.submittable.com/submit/338069/funding-request-2026','','','','','','Michelle Stoddart','Michelle Stoddart','','','Community Development Leader','Community Development Leader','','','michelle.stoddart@rwnewyork.com','michelle.stoddart@rwnewyork.com','','','resortworldgives'],
    ['Forest Hills Stadium Community Fund','Forest Hills and the greater Queens area','Education, health, culture, neighborhood beautification, and economic development','Forest Hills Application','To apply, applicants must:\n\n-Be a registered 501(c)(3) or a local school\n\n-Demonstrate a clear public benefit\n\n-Serve the Forest Hills area or greater Queens community\n\n-Submit a completed application via our online portal or email','Tier 1: up to $5000\nTier 2: $5000 - $10,000\nTier 3: $10,000 - $15,000','Rolling','Alexa Arrechi','Vice President','Alexa@lemmastrategies.com','26-4164715','In Progress','','','','','','','','','','','','','https://docs.google.com/forms/d/e/1FAIpQLSfN04-OLmr0PErxzvhKSl6hpGSBeUS9BmSlIq-NDzXIJxtjiw/viewform','','','','','','Alexa Arrechi','Alexa Arrechi','','','Vice President','Vice President','','','Alexa@lemmastrategies.com','Alexa@lemmastrategies.com','','','foresthillsstadiumcommunityfund'],
    ['CCNSF','New York City ','Education, immigrant communities, workforce development, low-income families, youth empowerment, community services',' Portal','Eligibility Requirements:\n\n• Must be registered in PASSPort.\n• Must have 501(c)(3) status and at least two years as an incorporated nonprofit.\n• Must be current with NYS Charities Bureau registration.\n• Must be an NYC-based direct social service organization serving primarily 75%+ NYC residents.\n• Must serve communities where 51%+ of the population are people of color.\n• Must have demonstrated outreach to communities of color for ED/CEO and board recruitment.\n• Operating budget must be at least $150,000 and no more than $3.5 million.\n• Fiscal sponsors/conduits are not eligible.\n\nDocument checklist:\n\n• Board of directors, officers, and affiliations.\n• Current fiscal year agency budget.\n• CHAR500 or proof of NYS Charities Bureau registration.\n• Most recent Form 990.\n• Most recent financial audit.\n• Executive Director resume.\n• Key program staff resumes.\n• Consultant resumes/company profile if consultants are used.','$45,000','October 17th','ALMIRCA SANTIAGO','','ASANTIAGO@HISPANICFEDERATION.ORG','11-2675971','','','','Sent Email','','','','','','','','','','https://www.ccnsfund.org/apply','','','','','','ALMIRCA SANTIAGO','ALMIRCA SANTIAGO','','','','','','','ASANTIAGO@HISPANICFEDERATION.ORG','ASANTIAGO@HISPANICFEDERATION.ORG','','','ccnsf'],
    ['M&T Charitable Fund','New York ','Community development, affordable housing, education, small business support, financial literacy, neighborhood revitalization','Portal','Eligibility requirements:\n• Organization must be a recognized 501(c)(3) public charity.\n• Must operate or serve individuals within cities/towns where M&T Bank conducts business.\n\nRequired documentation:\n• IRS determination letter.\n• Board of directors and affiliations.\n• Organization total annual operating budget, if requesting $10,000 or more.\n• List of other program donors, if requesting $10,000 or more.\n• Form 990, if requesting $10,000 or more.\n• Most current audited financials, if requesting $10,000 or more.','Varies','October 31st','Ade Escayg','','aescayg@mtb.com','16-1448017','','NG 9/29','','Sent Email to see eligibility','917-763-9442','','','','','','','','','','','','','','','','Ade Escayg','Ade Escayg','','','','','','','aescayg@mtb.com','aescayg@mtb.com','','','mtcharitablefund'],
    ['Banco Popular Foundation','Puerto Rico, U.S Virgin Islands, and United States ','Education, economic development, Puerto Rican/Latino communities, arts & culture, youth programs, community empowerment','Portal','Eligibility requirements:\n\n• Registered nonprofit, tax-exempt 501(c)(3) charitable organization.\n• Must provide meaningful volunteer opportunities for Popular employees.\n• Must integrate a Popular employee liaison.\n• Must economically empower individuals in the community.\n• Must use non-traditional learning environments and provide programs directly in communities.\n• Must demonstrate sustainability and program success.\n• Must be nondiscriminatory.\n• Proposal should show reasonable per-participant costs and request no more than 50% of funds for either general operating costs or staff salaries.','$10,000','August 31st, 2025','','','','47-4997597','','','Submitted 8/31','','','','','','','','','','','https://popular.fluxx.io/','','','','','','','','','','','','','','','','','','','bancopopularfoundation'],
]

URL_IDXS = [21, 23, 24, 25, 26, 27, 28]

def clean(v, maxlen=None):
    """Return blank for error/em-dash values; truncate if maxlen given."""
    if not v:
        return ''
    s = str(v).strip()
    if s in ('#ERROR!', '—', '–', '-', 'N/A'):
        return ''
    if maxlen and len(s) > maxlen:
        s = s[:maxlen]
    return s


def map_relationship(app_status):
    """Map Application Status text to Relationship__c picklist value."""
    s = app_status.lower().strip()
    if not s:
        return 'Prospect'
    if s.startswith('submitted') or 'loi submitted' in s:
        return 'Pending Funder'
    if 'in progress' in s:
        return 'Prospect'
    if s.startswith('ng') or 'declined' in s or 'not aligned' in s:
        return 'Declined Funding'
    return 'Prospect'

def research_links(row):
    """Use col 29 if valid, else join available URL cols."""
    if len(row) > 29:
        v = clean(row[29])
        if v:
            return v
    urls = []
    for i in URL_IDXS:
        if len(row) > i:
            v = clean(row[i])
            if v and v not in urls:
                urls.append(v)
    return '\n'.join(urls)

out_path = '/Users/mikeknight/Projects/love-migration/accounts.csv'
fields = [
    'Name', 'Account_External_ID__c', 'RecordTypeId',
    'Geographic_Scope__c', 'Area_of_Interest__c', 'Account_Information__c',
    'Documentation_Requirements__c', 'Grant_Amount_Text__c', 'Due_Date_Text__c',
    'TAX_ID_NUMBER__c', 'Submission_Status__c', 'Outreach_Status__c',
    'Internal_Notes__c', 'Research_Links__c', 'Relationship__c',
]

with open(out_path, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader()
    for row in ROWS:
        # External ID is a lowercase slug — find last matching value in the row
        import re as _re
        ext_id = next(
            (clean(v) for v in reversed(row)
             if _re.match(r'^[a-z0-9_]+$', str(v).strip())),
            ''
        )
        # pad row to at least 43 cols
        while len(row) < 43:
            row.append('')
        if not ext_id:
            print(f"WARNING: no External ID for {row[0]}", file=sys.stderr)
            continue
        notes_val = row[13] if len(row) > 13 else ''
        w.writerow({
            'Name': clean(row[0]),
            'Account_External_ID__c': ext_id,
            'RecordTypeId': ORG_RECORD_TYPE,
            'Geographic_Scope__c': clean(row[1]),
            'Area_of_Interest__c': clean(row[2]),
            'Account_Information__c': clean(row[3]),
            'Documentation_Requirements__c': clean(row[4]),
            'Grant_Amount_Text__c': clean(row[5]),
            'Due_Date_Text__c': clean(row[6]),
            'TAX_ID_NUMBER__c': clean(row[10]),
            'Submission_Status__c': clean(row[11]),
            'Outreach_Status__c': clean(row[12], maxlen=255),
            'Internal_Notes__c': clean(notes_val, maxlen=255),
            'Research_Links__c': research_links(row),
            'Relationship__c': map_relationship(clean(row[11])),
        })

print(f"Wrote {out_path}")
