"""L.O.V.E. Salesforce sync — reads source CSVs, upserts all objects.

Source CSVs are generated by Claude Code (reads Google Sheets via MCP).
This script handles transformation + idempotent SF upsert only.

Usage:
    python3 sync.py           # full sync
    python3 sync.py --dry-run # show what would happen, touch nothing
    python3 sync.py --step 4  # run only one step (1-9)

Steps:
    1  Org Accounts       (source: source_ready_for_accounts.csv)
    2  Org Contacts       (source: source_ready_for_contacts.csv)
    3  Org Opportunities  (source: source_ready_for_contacts.csv)
    4  Individual Accounts (source: source_indiv_*.csv)
    5  Individual Contacts
    6  Individual Opportunities
    7  Phase 2 Org Accounts   (source: source_p2_*.csv)
    8  Phase 2 Org Contacts
    9  Phase 2 Org Opportunities
"""
import argparse
import csv
import json
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request

PROJ   = '/workspace/Atlas/love-migration'

RT_HOUSEHOLD    = '012f2000000ww91AAA'
RT_ORGANIZATION = '012f2000000ww92AAA'

INDIV_TAB_INFO = [
    # (source_csv, prefix, email_cleanup_col, year_headers)
    ('source_indiv_board.csv',      'board',      'Email Cleanup',
     ['Amount donated 2026','Amount donated 2025','Amount donated 2024',
      'Amount donated 2023','Amount donated 2022','Amount donated 2021']),
    ('source_indiv_amigos.csv',     'amigos',     'Email Cleanup',
     ['2026','2025','2024','2023','2022']),
    ('source_indiv_campaneros.csv', 'campaneros', 'Email Clean Up',
     ['$2,026','$2,025','$2,024','$2,023','$2,022','2021']),
    ('source_indiv_aliados.csv',    'aliados',    'Email Clean Up',
     ['2026','2025','2024','2023','2022']),
]

# ── Helpers ───────────────────────────────────────────────────────────────────

def slugify(text):
    t = unicodedata.normalize('NFKD', str(text).strip())
    t = t.encode('ascii', 'ignore').decode('ascii')
    return re.sub(r'[^a-z0-9]', '', t.lower())


def clean_amount(v):
    v = str(v).strip()
    if not v or v in ('-', '—', '–', '$0', '0'):
        return ''
    v = re.sub(r'[$,\s]', '', v)
    v = re.split(r'[-–—]', v)[0].strip()
    try:
        f = float(v)
        return str(int(f)) if f > 0 else ''
    except ValueError:
        return ''


def clean_email(raw):
    raw = str(raw).strip()
    if not raw:
        return ''
    for c in re.split(r'[\s;,\n|]+', raw):
        c = c.strip()
        if '@' in c and '.' in c.split('@')[-1] and 'not.given' not in c:
            return c.lower()
    return ''


def is_blank(v):
    return str(v).strip() in ('', '—', '–', '-', 'N/A', 'None', '#ERROR!', '#REF!')


def truncate(v, n):
    return str(v)[:n] if v else ''


def map_relationship(status):
    s = str(status).strip().lower()
    if s.startswith('submitted') or s.startswith('loi'):
        return 'Pending Funder'
    if s.startswith('ng') or 'declined' in s:
        return 'Declined Funding'
    if 'granted' in s or 'closed won' in s:
        return 'Funder'
    return 'Prospect'


def map_stage(status):
    s = str(status).strip().lower()
    if s.startswith('loi'):
        return 'LOI Submitted'
    if s.startswith('submitted'):
        return 'Application Submitted'
    if s.startswith('ng') or 'declined' in s:
        return 'Closed Lost'
    if 'granted' in s or 'closed won' in s:
        return 'Closed Won'
    return 'Prospecting'


def parse_close_date(text):
    s = str(text).strip()
    if not s or s in ('Rolling', 'Open year-round', 'N/A', '2026 TBD', 'Varies', 'TBD'):
        return '2026-12-31'
    MONTHS = {
        'january':'01','february':'02','march':'03','april':'04',
        'may':'05','june':'06','july':'07','august':'08',
        'september':'09','october':'10','november':'11','december':'12',
    }
    m = re.search(r'(January|February|March|April|May|June|July|August|'
                  r'September|October|November|December)\s+(\d{1,2}),?\s*(\d{4})', s, re.I)
    if m:
        return f"{m.group(3)}-{MONTHS[m.group(1).lower()]}-{int(m.group(2)):02d}"
    m = re.search(r'(\d{1,2})/(\d{1,2})/(\d{4})', s)
    if m:
        return f"{m.group(3)}-{int(m.group(1)):02d}-{int(m.group(2)):02d}"
    m = re.search(r'(January|February|March|April|May|June|July|August|'
                  r'September|October|November|December)\s+(\d{1,2})', s, re.I)
    if m:
        return f"2026-{MONTHS[m.group(1).lower()]}-{int(m.group(2)):02d}"
    m = re.search(r'(\d{1,2})/(\d{1,2})', s)
    if m:
        return f"2026-{int(m.group(1)):02d}-{int(m.group(2)):02d}"
    return '2026-12-31'


def year_from_header(header):
    h = re.sub(r'[$,]', '', str(header))
    m = re.search(r'(20\d{2})', h)
    return int(m.group(1)) if m else None


# ── CSV / SF helpers ──────────────────────────────────────────────────────────

def read_csv(path):
    try:
        with open(path, newline='', encoding='utf-8') as f:
            return list(csv.DictReader(f))
    except FileNotFoundError:
        print(f"  ERROR: source file not found: {path}", file=sys.stderr)
        print(f"  Run Claude Code to regenerate source CSVs from Google Sheets.", file=sys.stderr)
        sys.exit(1)


def write_csv(path, fieldnames, rows):
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)
    return len(rows)


def _load_creds():
    creds_path = '/tmp/claude-501/love_creds.json'
    with open(creds_path) as f:
        c = json.load(f)
    return c['accessToken'], c['instanceUrl']


def sf_query(soql):
    token, instance = _load_creds()
    url = f"{instance}/services/data/v66.0/query?q={urllib.parse.quote(soql)}"
    req = urllib.request.Request(url, headers={'Authorization': f'Bearer {token}'})
    with urllib.request.urlopen(req) as r:
        data = json.loads(r.read())
    records = data.get('records', [])
    # handle pagination
    next_url = data.get('nextRecordsUrl')
    while next_url:
        req2 = urllib.request.Request(
            f"{instance}{next_url}",
            headers={'Authorization': f'Bearer {token}'},
        )
        with urllib.request.urlopen(req2) as r2:
            page = json.loads(r2.read())
        records.extend(page.get('records', []))
        next_url = page.get('nextRecordsUrl')
    return records


def sf_upsert(sobject, ext_field, csv_path, dry_run):
    if dry_run:
        with open(csv_path, newline='', encoding='utf-8') as f:
            n = sum(1 for _ in csv.reader(f)) - 1
        print(f"    [DRY RUN] Would upsert {n} {sobject} records via {ext_field}")
        return True
    token, instance = _load_creds()
    base = f"{instance}/services/data/v66.0/jobs/ingest"

    # Create bulk ingest job
    job_body = json.dumps({
        'object': sobject,
        'externalIdFieldName': ext_field,
        'contentType': 'CSV',
        'operation': 'upsert',
        'lineEnding': 'CRLF',
    }).encode()
    req = urllib.request.Request(
        base,
        data=job_body,
        headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'},
    )
    with urllib.request.urlopen(req) as r:
        job = json.loads(r.read())
    job_id = job['id']

    # Upload CSV data
    with open(csv_path, 'rb') as f:
        csv_data = f.read()
    upload_url = f"{base}/{job_id}/batches"
    req2 = urllib.request.Request(
        upload_url,
        data=csv_data,
        method='PUT',
        headers={'Authorization': f'Bearer {token}', 'Content-Type': 'text/csv'},
    )
    urllib.request.urlopen(req2).close()

    # Close the job (triggers processing)
    close_body = json.dumps({'state': 'UploadComplete'}).encode()
    req3 = urllib.request.Request(
        f"{base}/{job_id}",
        data=close_body,
        method='PATCH',
        headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'},
    )
    urllib.request.urlopen(req3).close()

    # Poll until done
    for _ in range(240):
        time.sleep(3)
        req4 = urllib.request.Request(
            f"{base}/{job_id}",
            headers={'Authorization': f'Bearer {token}'},
        )
        with urllib.request.urlopen(req4) as r4:
            status = json.loads(r4.read())
        state = status.get('state', '')
        if state in ('JobComplete', 'Failed', 'Aborted'):
            break
    ok = status.get('numberRecordsProcessed', 0)
    failed = status.get('numberRecordsFailed', 0)
    print(f"    Successful records: {ok - failed}")
    print(f"    Failed records: {failed}")
    print(f"    Processed records: {ok}")
    if failed:
        print(f"    WARNING: {failed} failed records in job {job_id}", file=sys.stderr)
    return state == 'JobComplete' and failed == 0


def resolve_ext_ids(ext_ids):
    out = {}
    for i in range(0, len(ext_ids), 200):
        batch = ext_ids[i:i+200]
        ids_str = "','".join(e.replace("'", "\\'") for e in batch)
        recs = sf_query(
            f"SELECT Id, Account_External_ID__c FROM Account "
            f"WHERE Account_External_ID__c IN ('{ids_str}')"
        )
        for r in recs:
            out[r['Account_External_ID__c']] = r['Id']
    return out


# ── Step 1: Org Accounts ──────────────────────────────────────────────────────

ORG_ACCT_FIELDS = [
    'Account_External_ID__c','Name','RecordTypeId','Geographic_Scope__c',
    'Area_of_Interest__c','Account_Information__c','Documentation_Requirements__c',
    'Grant_Amount_Text__c','Due_Date_Text__c','TAX_ID_NUMBER__c',
    'Submission_Status__c','Outreach_Status__c','Internal_Notes__c',
    'Research_Links__c','Relationship__c','Type',
]

def build_org_accounts(rows):
    out, seen = [], set()
    for row in rows:
        ext_id = str(row.get('Account1 External ID', row.get('External ID', ''))).strip()
        name   = str(row.get('Account1 Name', row.get('Name', ''))).strip()
        if not ext_id or not name:
            continue
        if ext_id in seen:
            continue
        seen.add(ext_id)
        rel = str(row.get('Relationship__c', row.get('Relationship', ''))).strip()
        if not rel:
            rel = map_relationship(str(row.get('Outreach_Status__c',
                                               row.get('Application Status', ''))))
        out.append({
            'Account_External_ID__c': ext_id,
            'Name': name,
            'RecordTypeId': RT_ORGANIZATION,
            'Geographic_Scope__c':            truncate(row.get('Geographic_Scope__c', row.get('Location','')), 255),
            'Area_of_Interest__c':            truncate(row.get('Area_of_Interest__c', row.get('Area of interest ','')), 32000),
            'Account_Information__c':         truncate(row.get('Account_Information__c', row.get('Account Information ','')), 32000),
            'Documentation_Requirements__c':  truncate(row.get('Documentation_Requirements__c', row.get('Documentation and Requirements ','')), 32000),
            'Grant_Amount_Text__c':           truncate(row.get('Grant_Amount_Text__c', row.get('Grant Amount','')), 255),
            'Due_Date_Text__c':               truncate(row.get('Due_Date_Text__c', row.get('Due Date','')), 255),
            'TAX_ID_NUMBER__c':               truncate(row.get('EIN',''), 20),
            'Submission_Status__c':           truncate(row.get('Outreach_Status__c', row.get('Application Status','')), 255),
            'Outreach_Status__c':             truncate(row.get('Outreach',''), 255),
            'Internal_Notes__c':              truncate(row.get('Internal_Notes__c', row.get('Notes','')), 32000),
            'Research_Links__c':              truncate(row.get('Research_Links__c',''), 255),
            'Relationship__c':                rel or 'Funder',
            'Type':                           str(row.get('Type', '')).strip(),
        })
    return out


# ── Step 2: Org Contacts ──────────────────────────────────────────────────────

ORG_CONT_FIELDS = ['Contact_External_ID__c','AccountId','FirstName','LastName','Title','Email']

MANUAL_MIGRATION_ACCOUNTS = {'compass(26026p0003)'}

def build_org_contacts(rows, ext_to_sfid):
    out, seen = [], {}
    for row in rows:
        ext_id = str(row.get('Account1 External ID', row.get('External ID',''))).strip()
        if not ext_id:
            continue
        if ext_id in MANUAL_MIGRATION_ACCOUNTS:
            continue
        sf_id = ext_to_sfid.get(ext_id, '')
        for i in range(1, 4):
            if i == 1:
                first = str(row.get('Contact 1First','')).strip()
                last  = str(row.get('Contact 1Last','')).strip()
                title = str(row.get('Title1 NameRaw','')).strip()
                email = str(row.get('Email1 NameRaw','')).strip()
            elif i == 2:
                first = str(row.get('Contact 2 First','')).strip()
                last  = str(row.get('Contact 2 Last','')).strip()
                title = str(row.get('Title2 NameRaw','')).strip()
                email = str(row.get('Email2 NameRaw','')).strip()
            else:
                first = str(row.get('Contact 3 First','')).strip()
                last  = str(row.get('Contact 3 Last','')).strip()
                title = str(row.get('Title3 NameRaw','')).strip()
                email = ''
            if is_blank(first) and is_blank(last):
                continue
            if 'claudia' in first.lower() and 'info' in last.lower():
                continue
            if first in ('—','–','-'):
                continue
            base = f"{ext_id}_c{i}"
            n = seen.get(base, 0) + 1
            seen[base] = n
            cont_ext = base if n == 1 else f"{base}_{n}"
            out.append({
                'Contact_External_ID__c': cont_ext,
                'AccountId': sf_id,
                'FirstName': first,
                'LastName':  last if not is_blank(last) else first,
                'Title':     truncate(title, 255),
                'Email':     clean_email(email),
            })
    return out


# ── Step 3: Org Opportunities ─────────────────────────────────────────────────

ORG_OPP_FIELDS = [
    'Opportunity_External_ID__c','Name','AccountId','StageName','CloseDate','Amount','Description',
]

def build_org_opps(rows, ext_to_sfid):
    out, seen = [], set()
    for row in rows:
        ext_id = str(row.get('Account1 External ID', row.get('External ID',''))).strip()
        name   = str(row.get('Account1 Name', row.get('Name',''))).strip()
        if not ext_id or not name:
            continue
        if ext_id in MANUAL_MIGRATION_ACCOUNTS:
            continue
        opp_eid = f"{ext_id}_opty"
        if opp_eid in seen:
            continue
        seen.add(opp_eid)
        sf_id  = ext_to_sfid.get(ext_id, '')
        status = str(row.get('Outreach_Status__c', row.get('Application Status',''))).strip()
        amount = clean_amount(row.get('Grant_Amount_Text__c', row.get('Grant Amount','')))
        due    = str(row.get('Due_Date_Text__c', row.get('Due Date',''))).strip()
        grant_text = str(row.get('Grant_Amount_Text__c', row.get('Grant Amount',''))).strip()
        out.append({
            'Opportunity_External_ID__c': f"{ext_id}_opty",
            'Name':        truncate(f"{name} Grant Application", 120),
            'AccountId':   sf_id,
            'StageName':   map_stage(status),
            'CloseDate':   parse_close_date(due),
            'Amount':      amount,
            'Description': truncate(f"Grant range: {grant_text}", 255) if grant_text else '',
        })
    return out


# ── Steps 4-6: Individual donors ─────────────────────────────────────────────

INDIV_ACCT_FIELDS = ['Account_External_ID__c','Name','RecordTypeId','Relationship__c']
INDIV_CONT_FIELDS = ['Contact_External_ID__c','FirstName','LastName','Email','MailChimp_Status__c','Note__c','AccountId']
INDIV_OPP_FIELDS  = ['Opportunity_External_ID__c','Name','StageName','CloseDate','Amount','AccountId']

def load_by_date_enrichment():
    """Load MailChimp, Note data from source_indiv_by_date.csv.
    Returns: dict mapping email -> {mailchimp, note}
    """
    enrichment = {}
    try:
        rows = read_csv(f'{PROJ}/source_indiv_by_date.csv')
        for row in rows:
            email = clean_email(str(row.get('Email Address', '')))
            if not email:
                continue
            mailchimp = str(row.get('MailChimp?', '')).strip()
            note = str(row.get('Note', '')).strip()
            enrichment[email] = {'mailchimp': mailchimp, 'note': note}
    except FileNotFoundError:
        pass  # No enrichment file available yet
    return enrichment


def build_indiv(dry_run=False):
    accts, conts, opps = [], [], []
    seen_dedup = {}  # Maps dedup key -> ext_id
    created_ext_ids = set()  # Track ext_ids we've already created Account/Contact for

    # Load enrichment data (MailChimp, Note)
    enrichment = load_by_date_enrichment()

    # Pass 1: Collect all rows and find best email per person (name-based key)
    all_rows = []
    name_to_email = {}  # Maps name-based key -> best email if available
    for src_csv, prefix, cleanup_col, year_headers in INDIV_TAB_INFO:
        rows = read_csv(f'{PROJ}/{src_csv}')
        for row in rows:
            first = str(row.get('First Name','')).strip()
            last  = str(row.get('Last Name','')).strip()
            if not first and not last:
                continue
            if 'not shared' in first.lower() and 'not shared' in last.lower():
                continue
            if first in ('—','–') and last in ('—','–'):
                continue

            all_rows.append((first, last, row, year_headers))

            # Track email by name-based key (full name); prefer any email over none
            name_key = (slugify(first), slugify(last))
            email = clean_email(str(row.get(cleanup_col, '')))
            if not email:
                email = clean_email(str(row.get('Email Address', '')))
            if email and not name_to_email.get(name_key):
                name_to_email[name_key] = email

    # Pass 2: Process rows with consolidated dedup keys
    for first, last, row, year_headers in all_rows:
        cleanup_col = None
        for src_csv, prefix_tmp, col, _ in INDIV_TAB_INFO:
            if str(row.get(col, '')):
                cleanup_col = col
                break
        if not cleanup_col:
            cleanup_col = 'Email Address'

        email = clean_email(str(row.get(cleanup_col, '')))
        if not email:
            email = clean_email(str(row.get('Email Address', '')))

        # Use consolidated email if available for name-based dedup
        name_key = (slugify(first), slugify(last))
        if not email and name_key in name_to_email:
            email = name_to_email[name_key]

        # Dedup key: email takes priority (most reliable), else name-based
        if email:
            dedup_key = ('email', email)
            base = f"indiv_{slugify(email)}"
        else:
            dedup_key = ('name', slugify(first), slugify(last))
            base = f"indiv_{slugify(first)}{slugify(last)}"

        # Reuse ext_id if this person already exists (from earlier row)
        if dedup_key in seen_dedup:
            ext_id = seen_dedup[dedup_key]
        else:
            # Generate new ext_id; handle name collisions with suffix
            n = 1
            ext_id = base
            while ext_id in created_ext_ids:
                n += 1
                ext_id = f"{base}_{n}"
            seen_dedup[dedup_key] = ext_id

        # Only create Account/Contact once per ext_id
        if ext_id not in created_ext_ids:
            household = f"{last} Household" if last else f"{first} Household"
            accts.append({
                'Account_External_ID__c': ext_id,
                'Name': household,
                'RecordTypeId': RT_HOUSEHOLD,
                'Relationship__c': 'Funder',
            })
            # Enrich contact with MailChimp and Note data if available
            cont_data = {
                'Contact_External_ID__c': ext_id,
                'FirstName': first,
                'LastName':  last if not is_blank(last) else first,
                'Email':     email,
                '_ext': ext_id,
            }
            if email in enrichment:
                mailchimp = enrichment[email].get('mailchimp', '')
                note = enrichment[email].get('note', '')
                if mailchimp:
                    cont_data['MailChimp_Status__c'] = mailchimp
                if note:
                    cont_data['Note__c'] = note
            conts.append(cont_data)
            created_ext_ids.add(ext_id)

        # Create Opportunities for each donation year
        full = f"{first} {last}".strip()
        year_amounts = {}  # Track amounts per year to handle duplicates
        for hdr in year_headers:
            year = year_from_header(hdr)
            if not year:
                continue
            amt = clean_amount(row.get(hdr, ''))
            if not amt:
                continue

            # Count occurrences of this amount in this year for this donor
            year_key = (year, amt)
            if year_key not in year_amounts:
                year_amounts[year_key] = 0
            year_amounts[year_key] += 1
            seq = year_amounts[year_key]

            # Ext ID includes amount; add sequence if multiple same-amount donations
            if seq == 1:
                opp_ext_id = f"{ext_id}_donation_{year}_{amt}"
            else:
                opp_ext_id = f"{ext_id}_donation_{year}_{amt}_{seq}"

            opps.append({
                'Opportunity_External_ID__c': opp_ext_id,
                'Name':      truncate(f"{full} Donation {year}", 120),
                'StageName': 'Closed Won',
                'CloseDate': f"{year}-12-31",
                'Amount':    amt,
                '_ext': ext_id,
            })

    return accts, conts, opps


# ── Phase 2 source files ─────────────────────────────────────────────────────

PHASE2_SOURCES = [
    'source_p2_foundation_grantors.csv',
    'source_p2_foundation_deadlines.csv',
    'source_p2_foundation_invite_only.csv',
    'source_p2_foundation_rolling.csv',
    'source_p2_foundation_reattempt.csv',
    'source_p2_foundation_2026.csv',
    'source_p2_foundation_not_applicable.csv',
    'source_p2_corporate_grantors.csv',
    'source_p2_corporate_potential.csv',
    'source_p2_corporate_rolling.csv',
    'source_p2_corporate_invite_only.csv',
    'source_p2_corporate_deadlines.csv',
    'source_p2_corporate_2026.csv',
]


def load_existing_sf_ext_ids():
    """Return set of Account_External_ID__c values already in SF."""
    recs = sf_query(
        "SELECT Account_External_ID__c FROM Account "
        "WHERE Account_External_ID__c != null"
    )
    return {r['Account_External_ID__c'] for r in recs}


def build_p2_ext_id(name, existing_ids):
    """Generate external ID from name; if it collides, return existing match."""
    slug = slugify(name)
    if slug in existing_ids:
        return slug
    # Also check common variants with & and . stripped
    for existing in existing_ids:
        if slugify(existing) == slug:
            return existing
    return slug


def build_p2_org_accounts(rows, existing_ids):
    out = []
    for row in rows:
        name = str(row.get('Name', '')).strip()
        if not name:
            continue
        ext_id = str(row.get('External ID', '')).strip()
        if not ext_id:
            ext_id = slugify(name)
        # If slug matches an existing ID, use that to avoid duplicates
        if ext_id not in existing_ids:
            for eid in existing_ids:
                if slugify(eid) == slugify(ext_id):
                    ext_id = eid
                    break
        rel = str(row.get('Relationship', '')).strip() or 'Prospect'
        # Derive Type from Source_Sheet__c prefix
        source_sheet = str(row.get('Source_Sheet__c', '')).strip()
        if source_sheet.startswith('Corporate'):
            acct_type = 'Corporate'
        elif source_sheet.startswith('Foundation'):
            acct_type = 'Foundation'
        elif source_sheet.startswith('Government'):
            acct_type = 'Government'
        elif source_sheet.startswith('ERG'):
            acct_type = 'Employee Resource Group'
        else:
            acct_type = ''
        out.append({
            'Account_External_ID__c': ext_id,
            'Name': name,
            'RecordTypeId': RT_ORGANIZATION,
            'Geographic_Scope__c':           truncate(row.get('Location', ''), 255),
            'Area_of_Interest__c':           truncate(row.get('Area of interest', ''), 32000),
            'Account_Information__c':        truncate(row.get('Account Information', ''), 32000),
            'Documentation_Requirements__c': truncate(row.get('Documentation and Requirements', ''), 32000),
            'Grant_Amount_Text__c':          truncate(row.get('Grant Amount', ''), 255),
            'Due_Date_Text__c':              truncate(row.get('Due Date', ''), 255),
            'TAX_ID_NUMBER__c':              truncate(row.get('EIN', ''), 20),
            'Submission_Status__c':          truncate(row.get('Application Status', ''), 255),
            'Outreach_Status__c':            truncate(row.get('Outreach', ''), 255),
            'Internal_Notes__c':             truncate(row.get('Internal_Notes__c', ''), 32000),
            'Research_Links__c':             truncate(row.get('Research_Links__c', ''), 255),
            'Relationship__c':               rel,
            'Type':                          acct_type,
        })
    return out


def build_p2_org_contacts(rows, existing_ids, ext_to_sfid):
    out, seen = [], {}
    for row in rows:
        name = str(row.get('Name', '')).strip()
        if not name:
            continue
        ext_id = str(row.get('External ID', '')).strip() or slugify(name)
        for eid in existing_ids:
            if slugify(eid) == slugify(ext_id):
                ext_id = eid
                break
        sf_id = ext_to_sfid.get(ext_id, '')
        for i in range(1, 4):
            if i == 1:
                full_name = str(row.get('Contact 1 NameRaw', '')).strip()
                title = str(row.get('Title1 NameRaw', '')).strip()
                email = str(row.get('Email1 NameRaw', '')).strip()
            elif i == 2:
                full_name = str(row.get('Contact2 NameRaw', '')).strip()
                title = str(row.get('Title2 NameRaw', '')).strip()
                email = str(row.get('Email2 NameRaw', '')).strip()
            else:
                full_name = str(row.get('Contact 3 NameRaw', '')).strip()
                title = str(row.get('Title3 NameRaw', '')).strip()
                email = str(row.get('Email3 NameRaw', '')).strip()
            if is_blank(full_name):
                continue
            if full_name in ('—', '–', '-', 'N/A') or re.match(r'^\d+\.$', full_name):
                continue
            parts = full_name.rsplit(' ', 1)
            first = parts[0].strip() if len(parts) > 1 else full_name.strip()
            last = parts[1].strip() if len(parts) > 1 else first
            base = f"{ext_id}_c{i}"
            n = seen.get(base, 0) + 1
            seen[base] = n
            cont_ext = base if n == 1 else f"{base}_{n}"
            out.append({
                'Contact_External_ID__c': cont_ext,
                'AccountId': sf_id,
                'FirstName': first,
                'LastName':  last,
                'Title':     truncate(title, 255),
                'Email':     clean_email(email),
            })
    return out


def build_p2_org_opps(rows, existing_ids, ext_to_sfid):
    out = []
    for row in rows:
        name = str(row.get('Name', '')).strip()
        if not name:
            continue
        ext_id = str(row.get('External ID', '')).strip() or slugify(name)
        for eid in existing_ids:
            if slugify(eid) == slugify(ext_id):
                ext_id = eid
                break
        sf_id    = ext_to_sfid.get(ext_id, '')
        status   = str(row.get('Application Status', '')).strip()
        amount   = clean_amount(row.get('Grant Amount', ''))
        due      = str(row.get('Due Date', '')).strip()
        grant_text = str(row.get('Grant Amount', '')).strip()
        out.append({
            'Opportunity_External_ID__c': f"{ext_id}_opty",
            'Name':        truncate(f"{name} Grant Application", 120),
            'AccountId':   sf_id,
            'StageName':   map_stage(status),
            'CloseDate':   parse_close_date(due),
            'Amount':      amount,
            'Description': truncate(f"Grant range: {grant_text}", 255) if grant_text else '',
        })
    return out


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be loaded without touching Salesforce')
    parser.add_argument('--step', type=int, choices=range(1,10),
                        help='Run only this step (1=org accts, 2=org contacts, '
                             '3=org opps, 4=indiv accts, 5=indiv contacts, 6=indiv opps, '
                             '7=p2 accts, 8=p2 contacts, 9=p2 opps)')
    parser.add_argument('--p2-source', metavar='FILE',
                        help='Phase 2: load a single source_p2_*.csv file instead of all')
    args = parser.parse_args()

    if args.dry_run:
        print('*** DRY RUN — no data written to Salesforce ***\n')

    run = lambda n: args.step is None or args.step == n

    # Load source data
    acct_src = read_csv(f'{PROJ}/source_ready_for_accounts.csv')
    cont_src = read_csv(f'{PROJ}/Source_ready_for_contacts.csv')

    # ── Step 1: Org Accounts ──────────────────────────────────────────────────
    if run(1):
        print('[1/6] Org Accounts')
        rows = build_org_accounts(cont_src or acct_src)
        path = f'{PROJ}/load_org_accounts.csv'
        n = write_csv(path, ORG_ACCT_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Account', 'Account_External_ID__c', path, args.dry_run)

    # Resolve org account IDs (needed for contacts + opps)
    org_ext_ids = [str(r.get('Account1 External ID', r.get('External ID',''))).strip()
                   for r in (cont_src or acct_src)]
    org_ext_ids = [x for x in org_ext_ids if x]
    if not args.dry_run and (run(2) or run(3)):
        print('  Resolving org account IDs...')
        org_ext_to_sfid = resolve_ext_ids(org_ext_ids)
    else:
        org_ext_to_sfid = {x: f'DRY_{x}' for x in org_ext_ids}

    # ── Step 2: Org Contacts ──────────────────────────────────────────────────
    if run(2):
        print('\n[2/6] Org Contacts')
        rows = build_org_contacts(cont_src or acct_src, org_ext_to_sfid)
        path = f'{PROJ}/load_org_contacts.csv'
        n = write_csv(path, ORG_CONT_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Contact', 'Contact_External_ID__c', path, args.dry_run)

    # ── Step 3: Org Opportunities ─────────────────────────────────────────────
    if run(3):
        print('\n[3/6] Org Opportunities')
        rows = build_org_opps(cont_src or acct_src, org_ext_to_sfid)
        path = f'{PROJ}/load_org_opps.csv'
        n = write_csv(path, ORG_OPP_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Opportunity', 'Opportunity_External_ID__c', path, args.dry_run)

    # ── Step 4: Individual Accounts ───────────────────────────────────────────
    if run(4) or run(5) or run(6):
        indiv_accts, indiv_conts, indiv_opps = build_indiv(args.dry_run)

    if run(4):
        print('\n[4/6] Individual Household Accounts')
        path = f'{PROJ}/load_indiv_accounts.csv'
        n = write_csv(path, INDIV_ACCT_FIELDS, indiv_accts)
        print(f'  {n} records')
        sf_upsert('Account', 'Account_External_ID__c', path, args.dry_run)

    # Resolve indiv account IDs
    indiv_ext_ids = [r['Account_External_ID__c'] for r in indiv_accts] if run(4) or run(5) or run(6) else []
    if not args.dry_run and (run(5) or run(6)):
        print('  Resolving individual account IDs...')
        indiv_ext_to_sfid = resolve_ext_ids(indiv_ext_ids)
    else:
        indiv_ext_to_sfid = {x: f'DRY_{x}' for x in indiv_ext_ids}

    # ── Step 5: Individual Contacts ───────────────────────────────────────────
    if run(5):
        print('\n[5/6] Individual Contacts')
        cont_load = []
        for r in indiv_conts:
            ext = r.pop('_ext')
            r['AccountId'] = indiv_ext_to_sfid.get(ext, '')
            cont_load.append(r)
        path = f'{PROJ}/load_indiv_contacts.csv'
        n = write_csv(path, INDIV_CONT_FIELDS, cont_load)
        print(f'  {n} records')
        sf_upsert('Contact', 'Contact_External_ID__c', path, args.dry_run)

    # ── Step 6: Individual Opportunities ─────────────────────────────────────
    if run(6):
        print('\n[6/6] Individual Opportunities')
        opp_load = []
        for r in indiv_opps:
            ext = r.pop('_ext')
            r['AccountId'] = indiv_ext_to_sfid.get(ext, '')
            opp_load.append(r)
        path = f'{PROJ}/load_indiv_opps.csv'
        n = write_csv(path, INDIV_OPP_FIELDS, opp_load)
        print(f'  {n} records')
        sf_upsert('Opportunity', 'Opportunity_External_ID__c', path, args.dry_run)

    # ── Steps 7-9: Phase 2 Org records ───────────────────────────────────────
    if run(7) or run(8) or run(9):
        import glob
        if args.p2_source:
            p2_files = [f'{PROJ}/{args.p2_source}']
        else:
            p2_files = sorted(glob.glob(f'{PROJ}/source_p2_*.csv'))
        if not p2_files:
            print('\nNo source_p2_*.csv files found — run Claude Code to generate them.')
        else:
            p2_rows = []
            for f in p2_files:
                rows_from_file = read_csv(f)
                # Tag each row with source filename for Type fallback
                import os
                fname = os.path.basename(f)
                for r in rows_from_file:
                    if not (r.get('Source_Sheet__c') or '').strip():
                        # Derive Source_Sheet__c from filename
                        # e.g. source_p2_foundation_grantors.csv → Foundation
                        if '_corporate_' in fname:
                            r['Source_Sheet__c'] = 'Corporate (from filename)'
                        elif '_foundation_' in fname:
                            r['Source_Sheet__c'] = 'Foundation (from filename)'
                        elif '_government_' in fname:
                            r['Source_Sheet__c'] = 'Government (from filename)'
                        elif '_erg_' in fname:
                            r['Source_Sheet__c'] = 'ERG (from filename)'
                p2_rows.extend(rows_from_file)

            if not args.dry_run:
                print('\n  Loading existing SF account IDs for dedup check...')
                existing_ids = load_existing_sf_ext_ids()
            else:
                existing_ids = set()

    if run(7):
        print('\n[7/9] Phase 2 Org Accounts')
        rows = build_p2_org_accounts(p2_rows, existing_ids)
        path = f'{PROJ}/load_p2_org_accounts.csv'
        n = write_csv(path, ORG_ACCT_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Account', 'Account_External_ID__c', path, args.dry_run)

    if not args.dry_run and (run(8) or run(9)):
        p2_ext_ids = [r['Account_External_ID__c'] for r in build_p2_org_accounts(p2_rows, existing_ids)]
        print('  Resolving Phase 2 account IDs...')
        p2_ext_to_sfid = resolve_ext_ids(p2_ext_ids)
    else:
        p2_ext_to_sfid = {}

    if run(8):
        print('\n[8/9] Phase 2 Org Contacts')
        rows = build_p2_org_contacts(p2_rows, existing_ids, p2_ext_to_sfid)
        path = f'{PROJ}/load_p2_org_contacts.csv'
        n = write_csv(path, ORG_CONT_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Contact', 'Contact_External_ID__c', path, args.dry_run)

    if run(9):
        print('\n[9/9] Phase 2 Org Opportunities')
        rows = build_p2_org_opps(p2_rows, existing_ids, p2_ext_to_sfid)
        path = f'{PROJ}/load_p2_org_opps.csv'
        n = write_csv(path, ORG_OPP_FIELDS, rows)
        print(f'  {n} records')
        sf_upsert('Opportunity', 'Opportunity_External_ID__c', path, args.dry_run)

    print('\n=== Sync complete ===')


if __name__ == '__main__':
    main()
